### ISSUE TITLE
Any suggestion on where to upload my own customized toots.css?

### ISSUE THREAD

**Issue by eclecticpassions** [sampsyo/emfed#17]
I'm having trouble getting anything to work other than the original `https://esm.sh/emfed@1.5.0/toots.css` link. I tried linking the "raw" css url from a personal repo on GitHub and DropBox but both won't work.

Currently I have this Mastodon feed embedded on my Wordpress blog, but the username and date is overlapping so I wanted to set `  .toot .user {
    display: inline;` to inline and also change a few colours and appearance settings. 

Can anyone help? Thanks a lot in advance.

**Comment by sampsyo** [comment]
Hmm, maybe you could provide a little more detail about what things look like in the Developer Tools? Can you check that (a) your CSS is actually being loaded, and that (b) the rules are actually getting applied? Sometimes I like to try something incredibly obvious like `.toot { background: pink; }` to see if the CSS is actually active at all…

**Comment by bibz** [comment]
When I used Wordpress in the past there was a way to directly enter [custom CSS in the settings](https://wordpress.com/support/editing-css/#access-the-css-editor). Did you try that too? For example with what @sampsyo suggests to make it obvious the rule is loaded on the page.

**Comment by eclecticpassions** [comment]
Thanks @sampsyo and @bibz!! I ended up using the [CSS Editor via Styles](https://wordpress.com/support/editing-css/#Access-the-CSS-Editor-(Global-Styles)) and pasted my changes in the "Additional CSS", and removed the line `<link rel="stylesheet" type="text/css" href="https://esm.sh/emfed@1/toots.css">` from the HTML embed. Thanks so much again. Have a great week.
