### ISSUE TITLE
too many toots displayed in some browsers

### ISSUE THREAD

**Issue by jhnc** [sampsyo/emfed#5]
https://sampsyo.github.io/emfed/ includes `data-toot-limit="4"` but 5 are shown in firefox and duckduckgo.

**Comment by acroyear** [comment]
I've found the cause of this.

     ` , o = s.dataset["toot-limit"] ?? "5"`
and
`      , c = s.dataset["toot-account-id"] ?? await (async()=>{`

datasets need to be accessed in camelCase, not hyphen-case

it should be s.dataset['tootLimit'] (or just s.dataset.tootLimit)
